services:
  # Service PHP
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: volume-and-length-app
    container_name: volume-and-length-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - './storage/app/public:/var/www/public/storage'
    ports:
      - "5173:5173"
    networks:
      - volume-and-length-net

  # Service MySQL
  volumeandlength-mysql:
    image: mysql:8.0
    container_name: volume-and-length-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - volume-and-length-mysql-data:/var/lib/mysql
    networks:
      - volume-and-length-net

  # Service Nginx
  volumeandlength-nginx:
    image: nginx:alpine
    container_name: volume-and-length-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - './storage/app/public:/var/www/public/storage'
    ports:
      - "8000:80"
    networks:
      - volume-and-length-net

networks:
  volume-and-length-net:

volumes:
  volume-and-length-mysql-data: